<?php

namespace GOL\ContentBundle\Repository;

/**
 * ConsumoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumoRepository extends \Doctrine\ORM\EntityRepository
{
}
