<?php

namespace GOL\ContentBundle\Repository;

/**
 * CostoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostoRepository extends \Doctrine\ORM\EntityRepository
{
}
