<?php

namespace GOL\ContentBundle\Repository;

/**
 * RecargaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecargaRepository extends \Doctrine\ORM\EntityRepository
{
}
